### ISSUE TITLE
Support PHP 8.1 in Pantheon recipe

### ISSUE THREAD

**Issue by jaydub2099** [lando/pantheon#132]
Pantheon supports PHP 8.1 on their platform but attempting to build a lando instance using the pantheon recipe with PHP 8.1 results in the following error:

ERROR: for appserver  manifest for devwithlando/pantheon-appserver:8.1-4 not found: manifest unknown: manifest unknown

I have updated my lando tree to attempt to use PHP 8.1 by updating the pantheon.xml file in my repo from reading:

php_version: 8.0
to
php_version: 8.1

and running lando rebuild.

From what I can tell, the issue here is that there is no PHP 8.1 docker image yet on docker hub which is where lando tries to download images (see https://hub.docker.com/r/devwithlando/pantheon-appserver/tags).

I asked Pantheon about PHP 8.1 and Lando as we are a client and they basically redirected us to the lando project. So I am wondering when we can expect lando to support PHP 8.1 when using the pantheon recipe.

**Comment by gaddman** [comment]
Tested this today and it works fine. There is a PHP 8.1 image on Docker hub, so that was probably the issue as you suggested.
