### ISSUE TITLE
Lando encodes local absolute path in all URLs 

### ISSUE THREAD

**Issue by spencerthayer** [lando/pantheon#143]
Please help, Lando is injecting the local URL into all links on the Pantheon server when pushing. This is breaking the Pantheon DEV, TEST, and LIVE sites because all media and other things are pointing to my computers local environment rather than the appropriate URL on Pantheon.

**Comment by spencerthayer** [comment]
This is a serious bug.

**Comment by pirog** [comment]
@spencerthayer what do you mean by injecting? If you are pushing your database up and your database contains references to lando locations then yes this can happen.

**Comment by ethangeorgi** [comment]
Assuming this issue has been resolve by now, and closing. If this issue persists, please provide more information.
