### ISSUE TITLE
Needed support for PHP 8.2

### ISSUE THREAD

**Issue by tyllyn** [lando/pantheon#159]
Began work locally on upgrading a Pantheon Drupal site to PHP 8.2, and adjusted the pantheon.yml as such:

```
api_version: 1
php_version: 8.2`
```

Upon attempting to rebuild with `lando rebuild`, I receive the following console output:

```
? Are you sure you want to rebuild? Yes
Rising anew like a fire phoenix from the ashes! Rebuilding app...
No stopped containers
Pulling appserver ... error
Pulling cache     ... done
Pulling database  ... done
Pulling edge      ... done
Pulling index     ... done

ERROR: for appserver  manifest for devwithlando/pantheon-appserver:8.2-2 not found: manifest unknown: manifest unknown
ERROR: manifest for devwithlando/pantheon-appserver:8.2-2 not found: manifest unknown: manifest unknown
ERROR ==>
```

**Comment by sharique** [comment]
How to update pantheon recipe to get PHP 8.2 support?

**Comment by reynoldsalec** [comment]
8.2 support was added in [v0.10.0 ](https://github.com/lando/pantheon/releases/tag/v0.10.0) of this plugin, and should be packaged with any Lando install from [v3.17.0](https://github.com/lando/cli/releases/tag/v3.17.0) onwards.

**Comment by reynoldsalec** [comment]
FYI, note that the correct way to use different PHP versions with the Pantheon recipe is to specify the version of PHP in your `pantheon.yml`...IE if you have PHP defined there, Lando should respect that (although you'll probably need to run a `lando rebuild` for it to take effect).
