### ISSUE TITLE
Cannot use lando init with pantheon recipe in versions 3.20.5 and 3.20.6

### ISSUE THREAD

**Issue by burkmarr** [lando/pantheon#208]
I have been using v3.20.4 but I need to update in order to overcome problems around working with pantheon and nginx. But with either version 3.20.5 or 3.20.6 I cannot use the pantheon recipe to initialise a project (see below). The `lando init` command no longer recognises the source 'pantheon'. Consequently I cannot work with any of my Pantheon repos which is a show-stopper. Is this an easy fix?

![image](https://github.com/lando/pantheon/assets/9275178/b4cca3c3-b0fc-4298-9a65-d25a9621536b)

**Comment by burkmarr** [comment]
With version 3.20.8 I can now use the Pantheon recipe. However there is a different problem which I shall report in a separate issue.

**Comment by reynoldsalec** [comment]
Going to close this out but please comment if it's still relevant @burkmarr, thanks!
