### ISSUE TITLE
Continued timeouts when trying to start project. 

### ISSUE THREAD

**Issue by not-original** [lando/pantheon#225]
![image](https://github.com/lando/lando/assets/1942426/dafe9367-93ff-4133-b262-a3d6e24acf1a)

Using Pantheon recipe with Wordpress.  I will run Lando Start, and the system runs through and starts docker with no problem.  Then it will cycle through the local urls 25 times, finally getting a 10000 MS Exceeded. 

If I run lando start again, SOMETIMES, it will finally connect and then I can develop.  What can I look at to change this and get it working on the first try?

**Comment by reynoldsalec** [comment]
@not-original if you try navigating to the URL before the healthcheck succeeds, do you get to the site?

**Comment by not-original** [comment]
> @not-original if you try navigating to the URL before the healthcheck succeeds, do you get to the site?

No, the site doesn't load.   After it goes through the checks (25 times),  I will wait a sec, then run Lando Start again -- and it usually goes green by the second or third check.

**Comment by reynoldsalec** [comment]
@not-original do you get an error code back when trying to access the URL while the scanner is failing?

Also curious if you run `lando start --debug` if you get any further information that appears relevant.

**Comment by not-original** [comment]
No error code, just that site cannot be reached and times out. 

The --debug info, doesn't add much more: (I only copied for the first 3 attempts)

wpt2  17:40:15 INFO ==> [STARTED] APPSERVER NGINX URLS
wpt2  17:40:15 INFO ==> [STARTED] https://localhost:60281
wpt2  17:40:15 INFO ==> [STARTED] http://localhost:60282
wpt2  17:40:15 INFO ==> [STARTED] http://wpt2.lndo.site/
wpt2  17:40:15 INFO ==> [STARTED] https://wpt2.lndo.site/
wpt2  17:40:19 DEBUG ==> scan of 'https://wpt2.lndo.site//' failed with 500 'Internal Server Error'
wpt2  17:40:19 DEBUG ==> scan of 'https://localhost:60281/' failed with 500 'Internal Server Error'
wpt2  17:40:19 DEBUG ==> scan of 'http://localhost:60282/' failed with 500 'Internal Server Error'
wpt2  17:40:19 DEBUG ==> scan of 'http://wpt2.lndo.site//' failed with 500 'Internal Server Error'
wpt2  17:40:20 INFO ==> [RETRY] https://wpt2.lndo.site/ [500] [1]
wpt2  17:40:20 INFO ==> [FAILED] Request failed with status code 500
wpt2  17:40:20 INFO ==> [RETRY] https://localhost:60281 [500] [1]
wpt2  17:40:20 INFO ==> [FAILED] Request failed with status code 500
wpt2  17:40:20 INFO ==> [RETRY] http://localhost:60282 [500] [1]
wpt2  17:40:20 INFO ==> [FAILED] Request failed with status code 500
wpt2  17:40:20 INFO ==> [RETRY] http://wpt2.lndo.site/ [500] [1]
wpt2  17:40:20 INFO ==> [FAILED] Request failed with status code 500
wpt2  17:40:30 DEBUG ==> scan of 'http://localhost:60282/' failed with 'TIMEOUT' 'unknown'
wpt2  17:40:30 DEBUG ==> scan of 'http://wpt2.lndo.site//' failed with 'TIMEOUT' 'unknown'
wpt2  17:40:30 DEBUG ==> scan of 'https://localhost:60281/' failed with 'TIMEOUT' 'unknown'
wpt2  17:40:30 DEBUG ==> scan of 'https://wpt2.lndo.site//' failed with 'TIMEOUT' 'unknown'
wpt2  17:40:31 INFO ==> [RETRY] http://localhost:60282 1/25 [TIMEOUT] [2]
wpt2  17:40:31 INFO ==> [FAILED] timeout of 10000ms exceeded
wpt2  17:40:31 INFO ==> [RETRY] http://wpt2.lndo.site/ 1/25 [TIMEOUT] [2]
wpt2  17:40:31 INFO ==> [FAILED] timeout of 10000ms exceeded
wpt2  17:40:31 INFO ==> [RETRY] https://localhost:60281 1/25 [TIMEOUT] [2]
wpt2  17:40:31 INFO ==> [FAILED] timeout of 10000ms exceeded
wpt2  17:40:31 INFO ==> [RETRY] https://wpt2.lndo.site/ 1/25 [TIMEOUT] [2]
wpt2  17:40:31 INFO ==> [FAILED] timeout of 10000ms exceeded
wpt2  17:40:41 DEBUG ==> scan of 'http://localhost:60282/' failed with 'TIMEOUT' 'unknown'
wpt2  17:41:21 DEBUG ==> scan of 'http://wpt2.lndo.site//' failed with 'TIMEOUT' 'unknown'
wpt2  17:41:21 DEBUG ==> scan of 'https://localhost:60281/' failed with 'TIMEOUT' 'unknown'
wpt2  17:41:21 DEBUG ==> scan of 'https://wpt2.lndo.site//' failed with 'TIMEOUT' 'unknown'
wpt2  17:41:22 INFO ==> [RETRY] http://localhost:60282 2/25 [TIMEOUT] [3]
wpt2  17:41:22 INFO ==> [FAILED] timeout of 10000ms exceeded
wpt2  17:41:22 INFO ==> [RETRY] http://wpt2.lndo.site/ 2/25 [TIMEOUT] [3]
wpt2  17:41:22 INFO ==> [FAILED] timeout of 10000ms exceeded
wpt2  17:41:22 INFO ==> [RETRY] https://localhost:60281 2/25 [TIMEOUT] [3]
wpt2  17:41:22 INFO ==> [FAILED] timeout of 10000ms exceeded
wpt2  17:41:22 INFO ==> [RETRY] https://wpt2.lndo.site/ 2/25 [TIMEOUT] [3]
wpt2  17:41:22 INFO ==> [FAILED] timeout of 10000ms exceeded

**Comment by reynoldsalec** [comment]
If you run `lando logs` do you see any additional output that seems related? Sometimes I like to look at the logs via Docker Desktop as well.

This sounds a bit like it could be some sort of weird app fatal, but that should show up in `lando logs -s appserver`

Could help to see your `.lando.yml` as well just to make sure there isn't anything special.

**Comment by reynoldsalec** [comment]
And if you haven't tried it already, the tried-and-true `lando rebuild` is always a good first-stop in weird problems, and of course you can always do the nuclear option: https://docs.lando.dev/help/purging-containers.html

**Comment by not-original** [comment]
> Could help to see your `.lando.yml` as well just to make sure there isn't anything special.

YML is pretty straight forward:

name: wpt2
recipe: pantheon
config:
  framework: wordpress
  site: wpt2
  id: dd9b8b45-35a0-4ed2-b5a1-332fd7b56eba
  edge: true

**Comment by not-original** [comment]
> And if you haven't tried it already, the tried-and-true `lando rebuild` is always a good first-stop in weird problems, and of course you can always do the nuclear option: https://docs.lando.dev/help/purging-containers.html

Tried the rebuild, but still no joy.   Still have to wait for the timeouts.

**Comment by reynoldsalec** [comment]
Might be worth disabling `edge` as well (`edge: false`) to see if that gives you any joy. 

Did those other lando log suggestions I gave you yield anything interesting?  https://github.com/lando/pantheon/issues/225#issuecomment-2046133939

**Comment by jt-mack** [comment]
Exact same thing happening for me, have tried all day and still same issue persists. It goes through all 25 retry attempts and is ultimately unsuccessful every time. @not-original did you ever get an answer or did you find a fix of your own? Appreciate any help, thank you

**Comment by not-original** [comment]
> Exact same thing happening for me, have tried all day and still same issue persists. It goes through all 25 retry attempts and is ultimately unsuccessful every time. @not-original did you ever get an answer or did you find a fix of your own? Appreciate any help, thank you

Two things I did that helped tremendously. 

1) I actually moved all of my sites out of windows, and into the linux instance.  This sped things up a LOT, so if you are running windows with WSL, try moving your sites to Linux -> Ubuntu -> home -> username -> lando (create this folder) -> nameofsite
This fixed my speed issue, as well as the scanning issue. 

2) If you don't prefer to move, or you are not having any speed issues, then you can set the scanning to FALSE in your lando yml.  For example:

name: yoursite
recipe: pantheon
config:
  framework: wordpress
  site: yoursite
  id: youridhere
  xdebug: false
  edge: false
  cache: false
services:
  appserver_nginx:
    scanner: false 

Setting that scanner to FALSE, will skip that step.    And let you start working right away.

Here is a good article about it:
https://danda.at/blog/how-to-get-rid-of-slow-health-checks-on-lando-start

Hope that helps!

**Comment by jt-mack** [comment]
@not-original thank you so much. Option 2 did work, but was still painfully slow. Went all in with option 1 and everything is working without any issues. Great stuff, I owe ya one!
