### ISSUE TITLE
Pantheon recipe error - machine token request

### ISSUE THREAD

**Issue by mtaggart-s-5** [lando/pantheon#233]
Hope you are having a great start to your week!

I submitted the crash report as well (around UTC 2024-04-02T16:19:39Z).  I wanted to report the following issue with the pantheon recipe:

My System information:
- Lando: v3.21.0-beta.12
- Docker version: 24.0.6, build ed223bc 
- Computer: Apple M1 Pro

Steps to replicate:
1. Using the lando recipe, input a newly created machine token directly in the terminal
2. See the resulting error

I have attempted the following:

```
lando init
? From where should we get your app's codebase? pantheon
? Enter a Pantheon machine token [hidden]
ERROR ==> POST request to authorize/machine-token failed with code 400: Bad Request. The server responded with the message Request to /delegation was not properly formatted. Error text: .
```

```
lando init
? From where should we get your app's codebase? current working directory
? What recipe do you want to use? pantheon
? Enter a Pantheon machine token [hidden]
ERROR ==> POST request to authorize/machine-token failed with code 400: Bad Request. The server responded with the message Request to /delegation was not properly formatted. Error text: .
```

What did I try?
1. Created new machine tokens.
2. Uninstalling Lando and reinstalling the lastest version using the recommended quickstart: `/bin/bash -c "$(curl -fsSL https://get.lando.dev/setup-lando.sh)"`

Please let me know if there is any other information I should add to this, or rename this issue as.

**Comment by mtaggart-s-5** [comment]
ooookay, I attempted to do this again utilitzing the steps I found in README.md here: https://github.com/lando/pantheon?tab=readme-ov-file#basic-usage and it started working.

Then I went back to the steps I was using before, and it started working...

I have no idea why, maybe even though Pantheon says they created the machine token, it takes 20 minutes or so for Pantheon to actually set up the newly created machine token?

That is my best guess.

**Comment by reynoldsalec** [comment]
Hmm, that hasn't been my experience in the past, although yesterday Pantheon did make some changes to their API backend. We had to push out a release for the Pantheon plugin to accommodate those changes, so anyone coming across this make sure you're on v1.14+ of the Pantheon plugin (IE run `lando update` if you're on Lando 3.21+).
