### ISSUE TITLE
Lando 3.21.0-beta12 with Pantheon recipe doesn't assign a port for external database connection

### ISSUE THREAD

**Issue by codyfishman** [lando/pantheon#237]
Initializing a directory using the Pantheon recipe on 3.20.8 would assign a port number for the external DB connection after running `lando start` + `lando info`. This would allow for a connection using a MySQL client. 
<img width="740" alt="image" src="https://github.com/lando/pantheon/assets/89869823/86ec21b5-835e-4e11-8fb3-44abef6de4c3">

This no longer happens with 3.21.0-beta12 and connecting using an external MySQL client isn't possible. 
<img width="740" alt="image" src="https://github.com/lando/pantheon/assets/89869823/d3a73564-f236-48ef-8b87-20dc5d9d7db1">

Other recipes on 3.21.0-beta12, like Wordpress, do provision the external connection port number. 
<img width="740" alt="image" src="https://github.com/lando/pantheon/assets/89869823/dc75a212-56d3-47be-abd1-6fe3c8b201d6">

**Comment by reynoldsalec** [comment]
Thanks for reporting @codyfishman, this came up on Slack as well, going to be pushing a fix shortly.

**Comment by reynoldsalec** [comment]
Fix should be available once you run `lando update` (provided you're on Lando 3.21+) to get the v1.4.1 version of the Pantheon plugin!
