### ISSUE TITLE
ImageMagick library cannot be found when PHP 8 is enabled

### ISSUE THREAD

**Issue by ptmkenny** [lando/pantheon#89]
Steps to reproduce:

1. Set up a Drupal 9 site on Pantheon and configure ImageMagick.
2. Use PHP 7.4 and set up Lando v3.6.0.  Go to `admin/config/media/image-toolkit`.  Everything works.
3. Update `pantheon.yml` to `php 8.0` and `lando rebuild`.  Go back to `admin/config/media/image-toolkit`.  Now, under **Version information**, Drupal gives an error:

`sh: 1: convert: not found`

**Comment by ptmkenny** [comment]
Closing as https://github.com/lando/pantheon/issues/90 noted that there is a pull request to fix this: https://github.com/lando/cli/pull/53

**Comment by alphex** [comment]
For those waiting on the pull request to go through, you can add the services block to .lando.yml seen here : https://github.com/lando/pantheon/issues/90#issuecomment-991770170
